permalink: pretty
theme: jekyll_patternbot
patternbot:
  call-to-action:
    fields: |
      - name: heading
        type: string
        example: "Delicious, amazing, coffee"
      - name: text
        type: string
        example: "You must get your hands on this coffee!!!"
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header and footer.
  title: "Coffee & Tea Essentials"
  description: The coffee is good.
  rationales:
    typefaces.primary: |
      Was chosen because it matches my serif, georgia.
    typefaces.secondary: |
      Was chosen beacause georgia is clean, bold, and easy to read.
    colors.primary: |
      Was chosen because it's easy on the eyes and a very elegant colour.
    colors.secondary: |
      Was chosen because it's neutral and goes with primary colour.
  collections:
    products:
      output: true

  defaults:
    -scope:
      path: _products
    values:
      layout: product
