title: "Header"
description: |
  Banners: top of page banners, call to action banners, sectional banners with large graphics

patterns:
  header:
    title: "Header"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
