title: "Header"
description: |
  The header is where you find the main nav and masthead.

patterns:
  header:
    title: "Header"
    description: |
      The header has all the pages for the webiste listed or in dropdown.
  header-banner:
    title: "Header Navigation Masthead Banner"
    description: |
      The header-naviagtion-masthead-banner inludes most of a home page: the main navigation, secondary navigation, masthead, and a banner.
  header-masterhead:
    title: "Masthead"
    description: |
      The Masthead is where the text and logo appears at the top of the screen.
  header-2:
    title: "Header Masthead"
    description: |
      This is what the header and masthead looks like together.
