title: "Photos"
description: |
  Photo arrays: how will you arrange the different photos for each product?

patterns:
  photo-array:
    title: "Photo Array"
    description: |
      Photo arrays: how will you arrange the different photos for each product?
