title: "Sections"
description: |
  Sections are areas on the webiste where information, or images are kept in groups.

patterns:
  info-section:
    title: "Information Sections"
    description: |
      This is a section to break up the home page or any of the pages with interesting information about the webiste; in this case the staff members. Can be used to advertise products, events or the company.

  photo-section:
    title: "Photo Sections"
    description: |
      The photo section has no text but gives the viewers a break from reading and more room to recognize the colour and design of the website.
