title: "Sections"
description: |
  Sections are areas on the webiste where information, or images are kept in groups.

patterns:
  info-section:
    title: "Information Sections"
    description: |
      This is a section to break up the home page or any of the pages with interesting information about the webiste; in this case the staff members. Can be used to advertise products, events or the company.

  photo-section:
    title: "Photo Sections"
    description: |
      The photo section has no text but gives the viewers a break from reading and more room to recognize the colour and design of the website.

    text-section:
      title: "Text Sections"
      description: |
        The text section has only text and had quick, simple and interesting facts about the webiste for the viewers. They need to stand out and allow the viewers to dive deeper into the site.
