title: "Forms"
description: |
  The following forms are required or handing for the cart page of a product website.

patterns:
  billing-form:
    title: "Billing Form"
    description: |
      The billing form is for adding all viewers credit card information to buy their items in cart.
  shipping-form:
    title: "Shipping Form"
    description: |
      The shipping form is to get their address to ship their products in their cart to them.
  member-form:
    title: "Member Form"
    description: |
      The member form is for those that are apart of the membership program and can get discounts or special emails after a purchase.
  promo-code:
    title: "Promo Code"
    description: |
      The promo code is where viewers can place special code for sales, holidays, or discounts that are vaild.
