title: "Homepage"
description: |
  The homepage has everything to attract a viewer to stay on the website. It needs a navigations system, call to action (to get viewers to dig deeper into the website or to purchase something), attractive content, and a footer.

patterns:
  homepage:
    title: "Homepage"
    description: |
