title: "Cards"
description: |
  Cards: image card, icon card, basic card, product info card, etc.

patterns:
  image-card:
    title: "Image Card"
    description: |
      This is a card where the image is more prominent then the text. Used to show off images of the store, staff, or products.
  icon-card:
    title: "Icon Card"
    description: |
      The icon card is used to show viewers the social media areas the company can be found in.
  product-info-card:
    title: "Product Info Card"
    description: |
      The product info card is a great use of images, icons, and text all in one. Where you see the image of the product, text explaining it, and icons showing rating and availability to shop.
  basic-card:
    title: "Basic Card"
    description: |
      The basic card only includes image and text; pretty standard.
