title: "Cards"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  image-card:
    title: "Image Card"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
  icon-card:
    title: "Icon Card"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
  product-info-card:
    title: "Product Info Card"
    description: |
      The icon button allows an icon to be seen for the action required.
  basic-card:
    title: "Basic Card"
    description: |
      The icon button allows an icon to be seen for the action required.
