title: "Navigation"
description: |
  Banners: top of page banners, call to action banners, sectional banners with large graphics.

patterns:
  top-of-page-nav:
    title: "Log In Navigation"
    description: |
      The top-of-page banner is good for quick descriptions, or company mottos that adds colour and depth.
  log-out-nav:
    title: "Log Out Navigation"
    description: |
      The top-of-page banner is good for quick descriptions, or company mottos that adds colour and depth.
