title: "navigation"
description: |
  Banners: top of page banners, call to action banners, sectional banners with large graphics.

patterns:
  top-of-page-nav:
    title: "Top of Page Navigation"
    description: |
      The top-of-page banner is good for quick descriptions, or company mottos that adds colour and depth.
  call-to-action:
    title: "Call to Action"
    description: |
      The call to action banner is to grad the viewers attention and is meant to get them to do something; click the button that is provided (for this one, the shop button).
