title: "Navigation"
description: |
  Secondary navigation is good for above or below header/main navigation (such as accounts informtion) and pages.

patterns:
  top-of-page-nav:
    title: "Log In Navigation"
    description: |
      The Log In Navigation is good for extra information that doesnt belong on main nav (such as account settings).
  log-out-nav:
    title: "Log Out Navigation"
    description: |
      The Log out Navigation is good for extra information that doesnt belong on main nav (such as account settings).
  pages-nav:
    title: "Pages Navigation"
    description: |
      The page sections is good for webiste landings with more than one page (product page), this allows viewers the ability to easily go to the previous or next page.
