title: "Banners"
description: |
  Banners: top of page banners, call to action banners, sectional banners with large graphics.

patterns:
  sectional:
    title: "Sectional"
    description: |
      This can be used for ads or space beside text on a web browser page if there is too much blank space. Instead of having everything take up the whole length of the page add a bit of grid work with some smaller sectional banners.
  top-of-page:
    title: "Top of Page"
    description: |
      The top-of-page banner is good for quick descriptions, or company mottos that adds colour and depth.
  banner:
    title: "Call to Action"
    description: |
      The call to action banner is to grad the viewers attention and is meant to get them to do something; click the button that is provided (for this one, the shop button).
    fields: |
      - name: heading
        type: string
        example: "Delicious, amazing, coffee"
      - name: text
        type: string
        example: "You must get your hands on this coffee!!!"
